### ISSUE TITLE
How do this plugin work?

### ISSUE THREAD

**Issue by ericmorand** [lukehorvat/browserify-cache#2]
Hi @lukehorvat, I know it's been a long time since you wrote that project, but I'd like to add filesystem caching support for those of us that don't use long-lived process on their tool chain - i.e. that recreates a Browserify instance on each build.

I have a hard time understanding how it works though.

The main logic is this `reset` function:

```js
  function reset() {
    b.pipeline.get("deps").push(through.obj(function(row, enc, callback) {
      var file = row.expose ? b._expose[row.id] : row.file;
      cache[file] = { source: row.source, deps: objectAssign({}, row.deps) };
      callback(null, row);
    }));
  }
```

But from my understanding, all it does is filling the cache. What is the magic behind this that makes the pipeline aware of this cache?

Thanks for your help.

Eric.

**Comment by lukehorvat** [comment]
IIRC the magic is in [module-deps](https://github.com/browserify/module-deps). A bit more info [here](https://github.com/browserify/browserify-handbook#deps). Does that help?

**Comment by ericmorand** [comment]
Thanks, that's it. Browserify passes all of its options to module-deps and module-deps accepts a `cache` option. That explains why one must pass an empty object as the `cache` option of Browserify even if the Browserify API makes no mention of this option.
